url: https://y7kim.github.io
baseurl: /TheClaussenGroup/

# Site settings
title: The Claussen Lab
email: lee901201@hotmail.com
description: "Please contact Prof. Claussen via email (jcclauss@iastate.edu) if you are interested in joining the group. We are currently looking for highly motivated postdocs, graduate students, and undergraduate students to join the group."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Suprem Das
  pic: 1
  position: Postdoc
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Shaowei Ding
  pic: 2
  position: PhD student
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Allison Cargill
  pic: 3
  position: MS student
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
- name: Bolin Chen
  pic: 4
  position: MS student
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Iowa State University
  - line: Ames,IA

# Build settings
markdown: kramdown
permalink: pretty